[package]
name = "nebula"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }

#candle feature
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.4.1", optional = true}
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.4.1", optional = true }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.4.1", optional = true }
tokenizers = { version = "0.15.2", optional = true }

#llama feature
llama-cpp = { path="backends/llama_cpp/llama-cpp", optional = true }

hf-hub = "0.3.2"
tracing-subscriber = "0.3.18"
tracing-chrome = "0.7.1"

thiserror = "1"
log = "0.4.17"

[features]
default = ["llama"]
llama = ["llama-cpp"]
candle = ["candle-core", "candle-transformers", "candle-nn", "tokenizers"]
cuda = ["llama-cpp?/cublas", "candle-core?/cuda", "candle-transformers?/cuda", "candle-nn?/cuda"]
