[package]
name = "llama-cpp-sys"
version = "0.0.1"
edition = "2021"

[dependencies]
lazy_static = "1.4"
libloading = "0.8"
thiserror = "1"
log = "0.4"

[build-dependencies]
lazy_static = "1.4"
cmake = "0.1"
bindgen = "0.69.4"
maplit = "1"
powershell_script = "1"
glob = "0.3"
