name: CI

on:
  push:
    branches:
      - main

jobs:
  test_nebula:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest

          - build: macos
            os: macos-latest

          - build: windows
            os: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

#      - name: Fetch LFS objects
#        run: git lfs fetch --all

#      - name: Pull LFS objects
#        run: git lfs pull

      - name: Update local toolchain
        run: |
          rustup update --no-self-update
          rustup component add clippy
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --features llama
      - name: Lint
        run: |
          #cd nebula
          #cargo fmt -- --check
          cargo clippy --features llama -- -D warnings
      - name: Test
        run: |
          #cd nebula
          cargo test --features llama
      - name: Build with llama
        run: |
          #cd nebula
          cargo build --release --features llama
