name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
      - main
      - release

jobs:
  test_nebula:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        include:
          - build: linux
            platform: ubuntu-latest

          - build: macos
            platform: macos-latest

          - build: windows
            platform: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      #      - name: Fetch LFS objects
      #        run: git lfs fetch --all

      #      - name: Pull LFS objects
      #        run: git lfs pull

      - name: Update local toolchain
        run: |
          rustup update --no-self-update
          rustup component add clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
      - name: Lint
        run: cargo clippy --features llama -- -D warnings

      - name: CpuInfo
        if: matrix.platform == 'ubuntu-latest'
        run: cat /proc/cpuinfo

      - name: Test
        run: cargo test --features "llama" -- --nocapture
